# Generated by Django 6.0.2 on 2026-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_menu_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='film',
            name='age_rating',
        ),
        migrations.AddField(
            model_name='film',
            name='age_rating_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст до'),
        ),
        migrations.AddField(
            model_name='film',
            name='age_rating_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст от'),
        ),
        migrations.AddField(
            model_name='film',
            name='categories',
            field=models.ManyToManyField(blank=True, to='content.filmcategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, to='content.genre', verbose_name='Жанры'),
        ),
    ]
