# Generated by Django 6.0.2 on 2026-02-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_populate_film_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип контента',
                'verbose_name_plural': 'Типы контента',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='content_types',
            field=models.ManyToManyField(blank=True, to='content.filmcontenttype', verbose_name='Тип контента'),
        ),
    ]
