# Generated by Django 6.0.2 on 2026-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_populate_film_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
    ]
