# Generated by Django 6.0.2 on 2026-02-27 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_film_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y/%m/', verbose_name='Файл')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фото в новости',
                'verbose_name_plural': 'Галерея новости',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
