# Generated by Django 6.0.2 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_banner_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок'),
        ),
    ]
