# Generated by Django 6.0.2 on 2026-03-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='sender_email',
            field=models.EmailField(blank=True, default='', help_text='Полный email для отправки (например, user@yandex.ru)', max_length=254, verbose_name='Email отправителя (Яндекс)'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='sender_password',
            field=models.CharField(blank=True, default='', help_text='Пароль приложения из настроек Яндекс аккаунта (не обычный пароль!)', max_length=255, verbose_name='Пароль приложения'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', help_text='Куда отправлять заявки', max_length=254, verbose_name='Email получателя'),
        ),
    ]
